### ISSUE TITLE
How to use NSLayoutConstraint.AutoSetPriority?

### ISSUE THREAD

**Issue by brightness007** [mallibone/PureLayout.Net#4]
This extension method requires an instance of NSLayoutConstraint. But in swift, it is used as class static method. How to use this method in Xamarin?

```
public static class NSLayoutConstraintPureLayout
{
        public static void AutoSetPriority(this NSLayoutConstraint This, float priority, [BlockProxy(typeof(NIDALConstraintsBlock))] ALConstraintsBlock block);
}
```

Code sample for using `NSLayoutConstraint.autoSetPriority` in swift.
```
NSLayoutConstraint.autoSetPriority(UILayoutPriorityDefaultHigh) {
    self.blueView.autoSetDimensions(to: CGSize(width: 10000.0, height: 10000.0))
}
```

**Comment by mallibone** [comment]
The extension method can be invoked when the layout constraints are being set. So for example you could do it like this:

```csharp
_tableView.AutoPinEdge(ALEdge.Bottom, ALEdge.Top, _clearHistoryButton).AutoSetPriority(1, () => {
    // ... additional code
 });
```

Hope this answers your question?

**Comment by brightness007** [comment]
Understood, Thank a lot!
